version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "24454:24454"
    environment:
      EULA: "true"
      MOD_PLATFORM: MODRINTH
      MEMORY: 8G
      MODRINTH_MODPACK: /packs/pack.mrpack
    volumes:
      - ./data:/data
      - /packs:/packs
